export const fieldData = [
  {
    field: "Donor ID / External ID",
    category: "Identity",
    object: "Contact / Account",
    type: "Text / External ID",
    description: "Stable identifier used to match donor records across systems.",
    quickbooks: "Yes",
    quickbooksParallel: "Customer ID or customer record identifier",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Household Name",
    category: "Identity",
    object: "Account / Household",
    type: "Text / Formula",
    description: "Groups spouses, partners, and family members for household-level giving and recognition.",
    quickbooks: "Partial",
    quickbooksParallel: "Customer display name, but household logic is limited",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Preferred Name",
    category: "Identity",
    object: "Contact",
    type: "Text",
    description: "Name used in personal communications and stewardship outreach.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "Maybe",
    mailchimp: "Yes",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Recognition Name",
    category: "Stewardship",
    object: "Contact / Household",
    type: "Text",
    description: "How the donor wants to be listed publicly in reports, event materials, or donor walls.",
    quickbooks: "Maybe",
    quickbooksParallel: "Customer display name or memo, but Salesforce is preferred",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Anonymous Giving Preference",
    category: "Stewardship",
    object: "Contact / Gift",
    type: "Checkbox / Picklist",
    description: "Flags donors or specific gifts that should not be publicly recognized.",
    quickbooks: "Maybe",
    quickbooksParallel: "Custom field or memo if needed for reporting",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Donor Status",
    category: "Strategy",
    object: "Contact",
    type: "Picklist",
    description: "Classifies donors as prospect, active, lapsed, recurring, major donor prospect, or inactive.",
    quickbooks: "No",
    quickbooksParallel: "None; fundraising strategy should remain in Salesforce",
    giveLively: "No",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Donor Type",
    category: "Identity",
    object: "Contact",
    type: "Picklist / Multi-select",
    description: "Identifies whether someone is an individual donor, board member, volunteer, event attendee, alumni, or partner.",
    quickbooks: "Maybe",
    quickbooksParallel: "Customer type or custom field if useful",
    giveLively: "No",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Relationship Owner",
    category: "Strategy",
    object: "Contact / Account",
    type: "Lookup / User",
    description: "Names the staff person responsible for managing the donor relationship.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Board / Staff Connector",
    category: "Engagement",
    object: "Contact",
    type: "Lookup / Text",
    description: "Tracks the person with the strongest existing relationship to the donor.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Connection Source",
    category: "Engagement",
    object: "Contact",
    type: "Picklist",
    description: "Captures how the donor first entered the organization’s network.",
    quickbooks: "No",
    quickbooksParallel: "Could be memo/custom field, but not recommended",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Primary Interest Area",
    category: "Engagement",
    object: "Contact",
    type: "Picklist",
    description: "The issue, program, or mission area most likely to motivate the donor.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "Maybe",
    mailchimp: "Yes",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Secondary Interest Areas",
    category: "Engagement",
    object: "Contact",
    type: "Multi-select Picklist",
    description: "Additional programs, campaigns, or topics the donor may care about.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "Maybe",
    mailchimp: "Yes",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Communication Preference",
    category: "Communications",
    object: "Contact",
    type: "Picklist",
    description: "Preferred channel for outreach: email, phone, mail, text, or no contact.",
    quickbooks: "Partial",
    quickbooksParallel: "Email, phone, and mailing address fields",
    giveLively: "Maybe",
    mailchimp: "Yes",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / Mailchimp",
  },
  {
    field: "Email Subscription Status",
    category: "Communications",
    object: "Contact",
    type: "Picklist / Synced Field",
    description: "Tracks whether the donor is subscribed, unsubscribed, cleaned, or pending in email marketing tools.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "Maybe",
    mailchimp: "Yes",
    priority: "Phase 1",
    sourceOfTruth: "Mailchimp",
  },
  {
    field: "Do Not Solicit",
    category: "Communications",
    object: "Contact",
    type: "Checkbox",
    description: "Prevents fundraising asks while potentially still allowing stewardship or required communications.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Cultivation Stage",
    category: "Strategy",
    object: "Contact / Opportunity",
    type: "Picklist",
    description: "Tracks where the donor is in the fundraising relationship: identify, qualify, cultivate, solicit, steward.",
    quickbooks: "No",
    quickbooksParallel: "None; do not sync cultivation strategy to accounting",
    giveLively: "No",
    mailchimp: "Maybe",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Giving Capacity Tier",
    category: "Strategy",
    object: "Contact",
    type: "Picklist",
    description: "Simple capacity range to support portfolio management and ask strategy.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Giving Inclination / Affinity",
    category: "Strategy",
    object: "Contact",
    type: "Picklist / Score",
    description: "Internal estimate of how likely a donor is to deepen their giving.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 3",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Next Best Action",
    category: "Strategy",
    object: "Contact / Task",
    type: "Text / Task",
    description: "The next recommended move with the donor: call, invite, thank, ask, introduce, or send update.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Next Ask Amount",
    category: "Strategy",
    object: "Contact / Opportunity",
    type: "Currency",
    description: "Potential future solicitation amount for planning purposes.",
    quickbooks: "No",
    quickbooksParallel: "None until a real gift or pledge exists",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Last Meaningful Contact Date",
    category: "Engagement",
    object: "Contact",
    type: "Date",
    description: "Most recent substantive interaction with the donor.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "Maybe",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Volunteer Interest",
    category: "Engagement",
    object: "Contact",
    type: "Picklist / Checkbox",
    description: "Indicates whether a donor is also interested in volunteering or hands-on engagement.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "Maybe",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Event Attendance History",
    category: "Engagement",
    object: "Campaign Member / Contact",
    type: "Related Records",
    description: "Tracks events attended and connects event participation to future giving.",
    quickbooks: "No",
    quickbooksParallel: "Only financial event transactions should sync",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Planned Giving Interest",
    category: "Strategy",
    object: "Contact",
    type: "Picklist / Checkbox",
    description: "Flags donors who have expressed interest in estate, legacy, or planned giving.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 3",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Gift Amount",
    category: "Gift / Transaction",
    object: "Opportunity / Gift Transaction",
    type: "Currency",
    description: "Amount of a gift, pledge, or payment.",
    quickbooks: "Yes",
    quickbooksParallel: "Transaction amount",
    giveLively: "Yes",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / Donation Platform",
  },
  {
    field: "Gift Date",
    category: "Gift / Transaction",
    object: "Opportunity / Gift Transaction / Payment",
    type: "Date",
    description: "Date the gift was received, committed, or transacted, depending on gift type rules.",
    quickbooks: "Yes",
    quickbooksParallel: "Transaction date",
    giveLively: "Yes",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / Donation Platform",
  },
  {
    field: "Gift Type",
    category: "Gift / Transaction",
    object: "Opportunity / Gift",
    type: "Picklist",
    description: "Classifies gift as one-time, recurring, pledge, event, sponsorship, in-kind, DAF, or stock.",
    quickbooks: "Maybe",
    quickbooksParallel: "Product/service item, income account, or memo",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Payment Method",
    category: "Gift / Transaction",
    object: "Payment / Gift Transaction",
    type: "Picklist",
    description: "Tracks check, ACH, credit card, cash, stock, DAF, or other payment types.",
    quickbooks: "Yes",
    quickbooksParallel: "Payment method",
    giveLively: "Yes",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / Donation Platform",
  },
  {
    field: "Transaction Reference Number",
    category: "Gift / Transaction",
    object: "Payment / Gift Transaction",
    type: "Text",
    description: "Check number, payment processor ID, or other transaction reference used for reconciliation.",
    quickbooks: "Yes",
    quickbooksParallel: "Check number, reference number, memo, or transaction ID",
    giveLively: "Yes",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Donation Platform / QuickBooks",
  },
  {
    field: "Campaign / Appeal",
    category: "Fundraising",
    object: "Campaign / Gift",
    type: "Lookup",
    description: "Connects a gift or donor to the fundraising campaign, event, mailing, or appeal that influenced giving.",
    quickbooks: "Maybe",
    quickbooksParallel: "Class, memo, custom field, or not synced",
    giveLively: "Maybe",
    mailchimp: "Yes",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Fund / Restriction / Designation",
    category: "Accounting",
    object: "Gift Allocation / Designation",
    type: "Lookup / Picklist",
    description: "Identifies restricted purpose, program, campaign, or fund for the gift.",
    quickbooks: "Yes",
    quickbooksParallel: "Class, sub-account, product/service item, or fund tracking structure",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / Finance-approved Mapping",
  },
  {
    field: "Revenue Category",
    category: "Accounting",
    object: "Gift / Opportunity",
    type: "Picklist",
    description: "Accounting category such as individual contribution, event ticket, sponsorship, grant, or in-kind.",
    quickbooks: "Yes",
    quickbooksParallel: "Income account or product/service item",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Finance-approved Mapping",
  },
  {
    field: "Tax-Deductible Amount",
    category: "Accounting",
    object: "Gift / Payment",
    type: "Currency",
    description: "Portion of the gift eligible for charitable acknowledgment after benefits or fair market value are considered.",
    quickbooks: "Maybe",
    quickbooksParallel: "Receipt detail, memo, or custom field if needed",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / Finance",
  },
  {
    field: "Fair Market Value of Benefits",
    category: "Accounting",
    object: "Gift / Payment",
    type: "Currency",
    description: "Value of goods or services received by the donor, such as event meals or tickets.",
    quickbooks: "Maybe",
    quickbooksParallel: "Receipt detail, memo, or custom field if needed",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce / Finance",
  },
  {
    field: "Acknowledgment Required",
    category: "Stewardship",
    object: "Gift / Payment",
    type: "Checkbox",
    description: "Indicates that a gift requires a thank-you, receipt, or stewardship action.",
    quickbooks: "No",
    quickbooksParallel: "Could be custom field, but stewardship should remain in Salesforce",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Acknowledgment Date",
    category: "Stewardship",
    object: "Gift / Payment",
    type: "Date",
    description: "Date the donor was thanked or receipted.",
    quickbooks: "No",
    quickbooksParallel: "Could be custom field, but not recommended as accounting data",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Acknowledgment Method",
    category: "Stewardship",
    object: "Gift / Payment",
    type: "Picklist",
    description: "Tracks whether donor was thanked by email, letter, phone call, personal note, or public recognition.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 2",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Receipt Number",
    category: "Accounting",
    object: "Gift / Payment",
    type: "Auto-number / Text",
    description: "Receipt or acknowledgment identifier that can be referenced by finance, development, and the donor.",
    quickbooks: "Yes",
    quickbooksParallel: "Sales receipt number or transaction number",
    giveLively: "Yes",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce / QuickBooks",
  },
  {
    field: "Deposit Batch ID",
    category: "Accounting",
    object: "Payment / Gift Batch",
    type: "Text",
    description: "Groups transactions that were deposited together to support reconciliation.",
    quickbooks: "Yes",
    quickbooksParallel: "Deposit reference, batch, memo, or bank deposit grouping",
    giveLively: "Maybe",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "QuickBooks / Finance",
  },
  {
    field: "QuickBooks Customer ID",
    category: "Integration",
    object: "Contact / Account",
    type: "Text / External ID",
    description: "Stores the linked QuickBooks customer record for donor/account matching.",
    quickbooks: "Yes",
    quickbooksParallel: "Customer ID",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "QuickBooks",
  },
  {
    field: "QuickBooks Transaction ID",
    category: "Integration",
    object: "Gift / Payment",
    type: "Text / External ID",
    description: "Stores the linked QuickBooks transaction after successful sync or manual reconciliation.",
    quickbooks: "Yes",
    quickbooksParallel: "Transaction ID",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "QuickBooks",
  },
  {
    field: "QuickBooks Sync Status",
    category: "Integration",
    object: "Gift / Payment",
    type: "Picklist",
    description: "Tracks whether a record is not synced, synced, failed, pending review, or intentionally excluded.",
    quickbooks: "N/A",
    quickbooksParallel: "Integration status field in Salesforce",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Sync Error Notes",
    category: "Integration",
    object: "Gift / Payment",
    type: "Long Text",
    description: "Captures integration failures or manual review notes.",
    quickbooks: "N/A",
    quickbooksParallel: "Integration/admin field, not an accounting field",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Source System",
    category: "Integration",
    object: "Contact / Gift",
    type: "Picklist",
    description: "Identifies whether the record originated in Salesforce, QuickBooks, Give Lively, Mailchimp, manual import, or spreadsheet migration.",
    quickbooks: "Maybe",
    quickbooksParallel: "Memo/custom field only if needed",
    giveLively: "Maybe",
    mailchimp: "Maybe",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Duplicate Review Needed",
    category: "Data Quality",
    object: "Contact / Account",
    type: "Checkbox",
    description: "Flags records that may need human review before syncing or stewardship activity.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 1",
    sourceOfTruth: "Salesforce",
  },
  {
    field: "Data Confidence Score",
    category: "Data Quality",
    object: "Contact / Gift",
    type: "Score / Picklist",
    description: "Internal rating of how reliable or complete the record is after migration or sync.",
    quickbooks: "No",
    quickbooksParallel: "None",
    giveLively: "No",
    mailchimp: "No",
    priority: "Phase 3",
    sourceOfTruth: "Salesforce",
  },
];

export const qbStrong = [
  ["Donor Name", "Customer record"],
  ["Gift Amount", "Transaction amount"],
  ["Gift Date", "Transaction date"],
  ["Payment Method", "Payment method"],
  ["Fund / Restriction", "Class, account, or item"],
  ["Revenue Category", "Income account or product/service"],
  ["Receipt Number", "Sales receipt number"],
  ["Deposit Batch ID", "Deposit reference or memo"],
  ["QuickBooks Transaction ID", "QuickBooks transaction record"],
];

export const qbWeak = [
  ["Cultivation Stage", "Fundraising strategy, not accounting"],
  ["Relationship Owner", "CRM ownership, not finance"],
  ["Donor Interests", "Segmentation and engagement, not reconciliation"],
  ["Next Ask Amount", "Planning field until a real pledge or gift exists"],
  ["Last Meaningful Contact", "Stewardship history, not accounting"],
  ["Volunteer Interest", "Engagement data, not accounting"],
];

export const phases = [
  {
    phase: "Phase 1",
    title: "Build the foundation",
    focus: "Identity, gift tracking, basic stewardship, and QuickBooks reconciliation.",
    fields: ["Donor ID", "Gift Amount", "Gift Date", "Fund / Restriction", "Acknowledgment Date", "QuickBooks IDs"],
  },
  {
    phase: "Phase 2",
    title: "Develop fundraising strategy",
    focus: "Relationship ownership, cultivation, interest areas, and proactive follow-up.",
    fields: ["Cultivation Stage", "Next Best Action", "Primary Interest Area", "Board / Staff Connector", "Event Attendance"],
  },
  {
    phase: "Phase 3",
    title: "Advance insight and automation",
    focus: "Scoring, segmentation, predictive insights, and more sophisticated donor journeys.",
    fields: ["Data Confidence Score", "Affinity Score", "Planned Giving Interest", "Engagement Scoring", "Lifetime Value"],
  },
];

export const reports = [
  {
    title: "Fundraising",
    examples: ["New donors this year", "Lapsed donors", "Recurring donor growth", "Major donor prospects", "Giving by campaign"],
  },
  {
    title: "Finance",
    examples: ["Gifts by fund", "Deposits needing review", "Missing QuickBooks IDs", "Tax-deductible totals", "Revenue category checks"],
  },
  {
    title: "Marketing",
    examples: ["Donors by interest area", "Event attendees who gave", "Newsletter donors", "Campaign clicks", "Segment growth"],
  },
  {
    title: "Leadership",
    examples: ["Individual giving pipeline", "Donor retention", "Revenue forecast", "Stewardship activity", "Top donor segments"],
  },
];

export const governanceQuestions = [
  "Who can create donor records?",
  "Who can edit financial gift records?",
  "Which fields are required at record creation?",
  "Which fields should be controlled picklists?",
  "Who owns duplicate review and cleanup?",
  "Who resolves failed QuickBooks syncs?",
  "What are campaign naming conventions?",
  "What are household naming conventions?",
  "How often should data quality be reviewed?",
];

export const openQuestions = [
  "What donor data from QuickBooks is reliable enough to migrate?",
  "Which fields should be required at gift entry versus optional over time?",
  "How should households, spouses, and family giving be handled?",
  "What is the right definition of active, lapsed, recurring, and major donor?",
  "Which fund or restriction values need to match finance reporting?",
  "What should happen when Salesforce and QuickBooks records do not match?",
  "How should donor-advised fund gifts, anonymous gifts, and event gifts be handled?",
  "Which reports are essential for leadership, finance, development, and marketing?",
];

export const nextSteps = [
  "Review existing QuickBooks donor and transaction exports.",
  "Inventory current spreadsheets, donation forms, and email lists.",
  "Confirm Salesforce object structure and field constraints.",
  "Prioritize Phase 1 fields for build and migration.",
  "Define QuickBooks sync requirements and exceptions.",
  "Define Mailchimp segmentation and subscription logic.",
  "Test a small sample of donor records and gift scenarios.",
  "Create data entry, duplicate review, and governance rules.",
];
